name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Node.js（必须 ≥16.9，推荐 18+）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 启用 Corepack 并自动安装 pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 缓存 pnpm 依赖
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 安装依赖（使用 pnpm）
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      # 构建
      - name: Build VuePress site
        run: pnpm docs:build

      # 部署
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/.vuepress/dist
